MENU_PRINCIPAL = """
=== MENU PRINCIPAL ===
=== ESCOLHA UMA DAS OPÇÕES ABAIXO ===
1. SAIR
2. GERENCIAR USUÁRIOS
3. GERENCIAR POSTAGENS
4. GERENCIAR CATEGORIAS
5. GERENCIAR COMENTÁRIOS
"""

MENU_USUARIOS = """
== MENU USUÁRIOS ==
== ESCOLHA UMA DAS OPÇÕES ABAIXO
1. VOLTAR AO MENU PRINCIPAL
2. CADASTRAR USUARIO
3. SELECIONAR USUARIO(S)
4. ATUALIZAR USUARIO
5. APAGAR USUARIO
"""

MENU_POSTAGENS = """
== MENU POSTAGENS ==
== ESCOLHA UMA DAS OPÇÕES ABAIXO
1. VOLTAR AO MENU PRINCIPAL
2. CADASTRAR POSTAGEM
3. SELECIONAR POSTAGEM(S)
4. ATUALIZAR POSTAGEM
5. APAGAR POSTAGEM
"""